export const city = [
  { tipTitle: "Getting to the city", tip: "Want to find the very best flight prices? If you’re flexible on when you fly, use Skyscanner’s ‘whole month’ search tool to find the cheapest day to travel to your chosen destination.", tip: "Hitchhiking is one of the cheapest ways of traveling. By tradition, hitchhiking is defined as asking for a ride by standing at the edge of a road, facing traffic, with one's thumb extended/upwards. You can meet a lot of people and make lots of friends.  People who do pick up hitchhikers tend to be very friendly. All the information needed you can find on hitchwiki website and especially helpful is a map with the best spots to get your car." },
  { tipTitle: "Getting around", tip: "Walking is your best option for saving money.  But if you are doing a lot of sightseeing in different parts of the city,  then a 24 hour ticket might be your best option since it allows unlimited travel for 24 hours from the time you purchase the ticket, and it costs just 8.80 euros for zones A & B.", tip: "Another cheap option for getting around is renting a bike or scooter. Berlin has seen a big increase in bicycle and scooter sharing companies, and now you can easily find one close to wherever you are." },
  { tipTitle: "Places to go", tip: "A hop on hop off bus tour does not always have to be expensive. With the 100 bus and a day ticket you can easily do your own city tour, get off at the most important sights or just admire the city as you drive by. Bus line 100 connects many of the city's important sights like Museum Island, the Reichstag, the Brandenburg Gate, Kaiser Wilhelm memorial church and so on.", tip: "It’s free to see Brandenburger Tor, the Victory Column, and the TV Tower, and it’s free to admire the East Side Gallery, one of the most popular places to see the Berlin Wall. Pass by Checkpoint Charlie, visit the Reichstag, pay respects at the Holocaust Memorial, and walk along the Unter den Linden avenue till you arrive to Germany’s tallest structure, the Fernseherturm.", tip: "This might not work for everyone, but if you can plan your trip to Berlin at the beginning of the month, you can take advantage of free museum Sundays." },
  { tipTitle: "Food", tip: "Buy food at the grocery store. Buying groceries can cut down on eating out if you’re backpacking in Berlin and trying to save money. You should look for Lidl, Penny, Netto, and Aldi supermarkets. These will have the lowest prices for groceries.", tip: "Get drinks at a Späti. Spätis are a Berlin convenience store. You’ll find them all over the city, and they’re normally open long hours, sometimes even 24 hours a day. At a Späti you can find beer and usually some other types of alcohol like wine or cocktails in cans.", tip: "Look for currywurst (great places are Curry 36 or Curry 61) or döner (Mustafa’s Gemüse Kebap or K’Ups Gemüsekebap) for a cheap meal. Not only are these foods you should try in Berlin, but they’re easy on the budget. There are Vietnamese restaurants all over the city, and you can often find some inexpensive food on the menu. And of course there are cheap pizza places and lots of other options.", tip: "When you’re sightseeing in Berlin, it’s best to have a refillable water bottle to take with you. This will be much cheaper than buying bottled water at a store. And yes, the tap water in Berlin is safe to drink."},
  { tipTitle: "Activities", tip: "You can certainly take one of the many free walking tours. You can choose from Sandeman’s New Europe and Brewer’s Berlin Tours — these tours will hit many of the highlights, but don’t forget to tip.", tip: "Sundays are for flea markets in Berlin. Dozens of flea markets pop up in squares and parks all over the city, and even if you have no intention to buy anything, they can be really interesting to wander through and see what sorts of odd items are for sale. Mauerpark is one of the most well known, but there are tons of others, such as Boxhaganer Platz and Prinzessinenngärten.", tip: "Check out Tempelhofer Park. Today you can enjoy walking, running, roller blading, cycling, kite surfing, and more all on a former airport runway. There are grassy areas where you can have a picnic, gardening areas, fenced dog areas, bird protection areas, and more.", tip: "Berlin has lots of excellent beer gardens, and it’s a great way to relax and soak up the local atmosphere. The nicest are Prater Beer Garden and Weihenstephaner.", tip: "Berlin is one of the best cities in the world for clubbing, so if you’re into techno, dancing, and having a wild and crazy night, you’ve come to the right place."},
  { tipTitle: "Where to stay", tip: "Couchsurfing is the best way to stay with locals, make lifelong travel friends, or host travelers coming to your hometown. It works by people offering up their sofas, floors, spare rooms and so on for travellers to sleep on for free. It really helps to have someone who knows everything about the city! Moreover there is a weekly meet up every Thursday in Berlin!", tip: "If you don’t feel comfortable with using Couchsurfing, the best way to find the cheapest hostels to stay is through Booking. Here are some of the best-rated hostels in Berlin: EastSeven Berlin Hostel, Wombats City Hostel Berlin and The Circus Hostel."}
];
export const city2 = [
  { tipTitle: "Activities", tip: "Visit the Louvre for free — Admission to the famous Louvre Museum is free the first Sunday of each month from October to March. It’s also free on Friday evenings for anyone under 26. ", tip: "Visit the free sights — The city has a lot of free attractions, including museums (like the Musée d’Art Moderne, Maison de Balzac, and Maison de Victor Hugo), most churches, and parks (like the Jardin du Luxembourg).", tip: "Take a free walking tour — Free walking tours of Paris’s central sights are available from several tour companies. Definitely check out New Europe Walking Tours. " },
  { tipTitle: "Food", tip: "Pick up lunch at outdoor markets — Paris is a market city, with food markets throughout town. If you want to save big money on meals, head to one of the markets, pick up some cheese, wine, bread, meats, or anything else, and head to the park for a picnic. ", tip: "Head to the grocery store for basics — Grocery shopping is a no-brainer way to eat cheap. They have all the ingredients you need for basic meals as well as prepared meals. They sell wine too!", tip: "Eat away from the tourist centers – Always walk five blocks away from any tourist sight to find good local cuisine. Some good areas to eat are the Latin Quarter, Bastille, Monmarte, Le Marias, 5th, and 13th." },
  { tipTitle: "Accomodation", tip: "" },
];
